import { Product } from '../types/navigation'; // Import the existing Product type

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Textbook: Introduction to Computer Science',
    price: 45000,
    image: 'https://picsum.photos/400/500',
    category: 'Textbooks',
    condition: 'Like New',
    sellerVerified: true,
    description: 'Comprehensive textbook covering all fundamental concepts of computer science. Barely used, no markings.',
    datePosted: '3 days ago',
  },
  {
    id: '2',
    title: 'Scientific Calculator',
    price: 15000,
    image: 'https://picsum.photos/400/501',
    category: 'Electronics',
    condition: 'Good',
    sellerVerified: false,
    description: 'Casio FX-991EX scientific calculator. Perfect for engineering and science courses. Minor scratches on the back.',
    datePosted: '1 week ago',
  },
  {
    id: '3',
    title: 'Dorm Room Chair',
    price: 25000,
    image: 'https://picsum.photos/400/502',
    category: 'Dorm & Home',
    condition: 'Like New',
    sellerVerified: true,
    description: 'Comfortable ergonomic chair, ideal for studying. Adjustable height and lumbar support. No stains or tears.',
    datePosted: '5 days ago',
  },
  {
    id: '4',
    title: 'Chemistry Lab Kit',
    price: 35000,
    image: 'https://picsum.photos/400/503',
    category: 'Other',
    condition: 'Good',
    sellerVerified: false,
    description: 'Complete chemistry lab kit with beakers, test tubes, and other essentials. Used for one semester.',
    datePosted: '2 weeks ago',
  },
  // Add a few more diverse products for better "Related Items" testing
  {
    id: '5',
    title: 'Wireless Headphones',
    price: 75000,
    image: 'https://picsum.photos/400/504',
    category: 'Electronics',
    condition: 'New',
    sellerVerified: true,
    description: 'Brand new Sony WH-1000XM4 noise-cancelling headphones. Sealed box. Unwanted gift.',
    datePosted: 'Yesterday',
  },
  {
    id: '6',
    title: 'Study Lamp',
    price: 12000,
    image: 'https://picsum.photos/400/505',
    category: 'Dorm & Home',
    condition: 'Good',
    sellerVerified: false,
    description: 'Adjustable LED study lamp with multiple brightness settings. Provides excellent illumination for late-night study sessions.',
    datePosted: '10 days ago',
  },
  {
    id: '7',
    title: 'Vintage University Jacket',
    price: 30000,
    image: 'https://picsum.photos/400/506',
    category: 'Fashion',
    condition: 'Like New',
    sellerVerified: true,
    description: 'Rare vintage university jacket from the 90s. Excellent condition, a true collector\'s item.',
    datePosted: '4 days ago',
  },
  {
    id: '8',
    title: 'Advanced Calculus Textbook',
    price: 55000,
    image: 'https://picsum.photos/400/507',
    category: 'Textbooks',
    condition: 'Good',
    sellerVerified: false,
    description: 'Stewart\'s Calculus, 8th Edition. Some highlighting in early chapters, otherwise good condition.',
    datePosted: '6 days ago',
  },
]; 